name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: yasar2019/my_docker_image:latest

    - name: Run tests
      run: |
        docker run yasar2019/my_docker_image:latest pytest

    - name: Run code analysis and formatting checks
      run: |
        docker run yasar2019/my_docker_image:latest pylint src/*.py
        docker run yasar2019/my_docker_image:latest black --check src/*.py

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          yasar2019/my_docker_image:latest
          yasar2019/my_docker_image:${{ github.run_number }}
